// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ1hwn81dnn8CLkSQ2v6hEQaOLHBy61iU',
    appId: '1:59261150549:web:a7292c46b4d9416ac37bdc',
    messagingSenderId: '59261150549',
    projectId: 'week-5-task',
    authDomain: 'week-5-task.firebaseapp.com',
    storageBucket: 'week-5-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJxopeeiY96apnqKSdBiQuyoEp0qGc-mk',
    appId: '1:59261150549:android:4f97485ef0e1e1afc37bdc',
    messagingSenderId: '59261150549',
    projectId: 'week-5-task',
    storageBucket: 'week-5-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9E6x9dFLo3EebIhaoB1zFt2OwgGw-03U',
    appId: '1:59261150549:ios:60095f30de5df0ffc37bdc',
    messagingSenderId: '59261150549',
    projectId: 'week-5-task',
    storageBucket: 'week-5-task.appspot.com',
    iosClientId: '59261150549-8mo56esebm5akn0b1oh5n2ouc9crcp8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.week5Task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9E6x9dFLo3EebIhaoB1zFt2OwgGw-03U',
    appId: '1:59261150549:ios:60095f30de5df0ffc37bdc',
    messagingSenderId: '59261150549',
    projectId: 'week-5-task',
    storageBucket: 'week-5-task.appspot.com',
    iosClientId: '59261150549-8mo56esebm5akn0b1oh5n2ouc9crcp8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.week5Task1',
  );
}
